import { Iproduct } from './iproduct';

export const productsList: Iproduct[] = [
  {
    imgSrc:'9.jpg',
    id: 1,
    name: 'suits Collections',
    price: 1000,
    quantity: 100,
  },
  {
    imgSrc:'15.webp',
    id: 2,
    name: 'suits Collections',
    price: 900,
    quantity: 50,
  },
  {
    imgSrc:'11.jpeg',
    id: 3,
    name: 'suits Collections',
    price: 800,
    quantity: 50,
  },
  {
    imgSrc:'12.jpg',
    id: 4,
    name: 'suits Collections',
    price: 1200,
    quantity: 100,
  },
  {
    imgSrc:'13jpg.jpg',
    id: 5,
    name: 'suits Collections',
    price: 1000,
    quantity: 40,
  },

  {
    imgSrc:'14.webp',
    id: 6,
    name: 'suits Collections',
    price: 1500,
    quantity: 10,
  },
  {
    imgSrc:'10.jpg',
    id: 7,
    name: 'suits Collections',
    price: 1800,
    quantity: 60,
  },
  {
    imgSrc:'16webp.webp',
    id: 8,
    name: 'suits Collections',
    price: 1000,
    quantity: 100,
  },
  {
    imgSrc:'1.jpg',
    id: 9,
    name: 'Kids Collections',
    price: 800,
    quantity: 60,
  },
  {
    imgSrc:'2.jpeg',
    id: 10,
    name: 'Kids Collections',
    price: 450,
    quantity: 80,
  },
  {
    imgSrc:'3.jpeg',
    id: 11,
    name: 'Kids Collections',
    price: 900,
    quantity: 50,
  },
  {
    imgSrc:'4.jpg',
    id: 12,
    name: 'Kids Collections',
    price: 350,
    quantity: 40,
  },
  {
    imgSrc:'5.jpeg',
    id: 13,
    name: 'Kids Collections',
    price: 600,
    quantity: 30,
  },
  {
    imgSrc:'6.jpg',
    id: 14,
    name: 'Kids Collections',
    price: 300,
    quantity: 100,
  },
  {
    imgSrc:'7.jpg',
    id: 15,
    name: 'Kids Collections',
    price: 100,
    quantity: 200,
  },
  {
    imgSrc:'8.avif',
    id: 16,
    name: 'Kids Collections',
    price: 280,
    quantity: 100,
  },
  {
    imgSrc:'17.jpg',
    id: 17,
    name: 'Women Collections',
    price: 500,
    quantity: 20,
  },
  {
    imgSrc:'18.jpeg',
    id: 18,
    name: 'Women Collections',
    price: 900,
    quantity: 100,
  },
  {
    imgSrc:'19.jpg',
    id: 19,
    name: 'Women Collections',
    price: 400,
    quantity: 150,
  },
  {
    imgSrc:'20.jpg',
    id: 20,
    name: 'Women Collections',
    price: 800,
    quantity: 50,
  },
  {
    imgSrc:'21ws.jpg',
    id: 21,
    name: 'Women Collections',
    price: 700,
    quantity: 90,
  },
  {
    imgSrc:'22jpg.jpg',
    id: 22,
    name: 'Women Collections',
    price: 500,
    quantity: 100,
  },
  {
    imgSrc:'321.jpg',
    id: 23,
    name: 'Women Collections',
    price: 800,
    quantity: 150,
  },
  {
    imgSrc:'24.jpg',
    id: 24,
    name: 'Women Collections',
    price: 300,
    quantity: 50,
  },
];

